name: on-master go build/test publish container

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'

jobs:
  build-publish:
    name: go build test fmt check
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Init gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - run: gcloud info

    - name: private key to file
      env:
        PRIVATE_PEM: ${{ secrets.PRIVATE_KEY_PEM }}
      run: |-
        echo "$PRIVATE_PEM" | base64 -d > github-private-key.pem

    - name: look in path
      run: |-
        ls $GOOGLE_APPLICATION_CREDENTIALS && \
        pwd && \
        ls


    - name: run rulla nycklar
      run: |-
        docker run \
            -v $GOOGLE_APPLICATION_CREDENTIALS:/credentials.json \
            -v $(pwd)/github-private-key.pem:/private-key.pem \
            --entrypoint /bin/github-rulla-nycklar \
            quay.io/shelman/github-rulla-nycklar:latest \
              --github-key-file="/private-key.pem" \
              --github-app-id=62880 \
              --github-install-id=8467539 \
              --owner=shelmangroup \
              --log-level=info \
              --repo-to-email="test-foo=github-test-foo@xXxXx.iam.gserviceaccount.com" \
              --repo-to-email="test-bar=github-test-bar@xXxXx.iam.gserviceaccount.com" \
              --secret-name="GCP_SERVICE_ACCOUNT_KEY"
