name: on-master go build/test publish container

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'

jobs:
  build-publish:
    name: go build test fmt check publish container
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.EMAIL }}
        service_account_key: ${{ secrets.KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build
      run: make container        

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: make container-push
        
